add debug output to slicing component because it breaks at user 82
<--- Last few GCs --->

   48947 ms: Scavenge 1394.4 (1433.0) -> 1394.4 (1433.0) MB, 2.9 / 0 ms (+
   4.0 ms in 1 steps since last GC) [allocation failure] [incremental
   marking delaying mark-sweep].
      49236 ms: Mark-sweep 1394.4 (1433.0) -> 999.4 (1037.2) MB, 289.4 / 0
      ms (+ 5.0 ms in 2 steps since start of marking, biggest step 4.0 ms)
      [last resort gc].
         49462 ms: Mark-sweep 999.4 (1037.2) -> 999.0 (1037.2) MB, 226.3 /
	 0 ms [last resort gc].

	 <--- JS stacktrace --->

	 ==== JS stack trace =========================================

	 Security context: 00000300C75B4639 <JS Object>
	     2: map_extrema_lists(aka map_extrema_lists)
	     [C:\Users\User\Documents\Projects\signature-recognition\private\evaluation\dtw_slicing_evaluation.js:~275]
	     [pc=000002A24D82A0FA] (this=00000300C75041B9
	     <undefined>,list_s=0000029D7D593E69 <JS
	     Array[9]>,list_t=0000029D7D593E89 <JS Array[9]>)
	         3: compute_slicing_result(aka compute_slicing_result)
		 [C:\Users\User\Documents\Projects\signature-reco...

		 FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed -
		 process out of memory